service: login-app

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  memorySize: 256
  environment:
    MONGO_URL: ${env:MONGO_URL}

functions:
  login:
    handler: login.handler
    events:
      - httpApi:
          path: /login
          method: post
  register: 
    handler: register.handle
    events:
      - httpApi:
          path: /register
          method: post

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000