service: login-app

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  memorySize: 256
  environment:
    MONGO_URL: ${env:MONGO_URL}
    JWT_SECRET: ${env:JWT_SECRET}
  httpApi:
    authorizers:
      authorizeToken:
        type: request
        functionName: authorizerFunc
        identitySource: 
          - $request.header.Authorization
        resultTtlInSeconds: 300

functions:
  login:
    handler: login.handler
    events:
      - httpApi:
          path: /login
          method: post
  register: 
    handler: register.handler
    events:
      - httpApi:
          path: /register
          method: post
  profile:
    handler: profile.handler
    events:
      - httpApi:
          path: /profile
          method: get
          authorizer:
            name: authorizeToken
  authorizerFunc:
    handler: utils/auth.handler

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000