service: login-app

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  memorySize: 256
  environment:
    MONGO_URL: ${env:MONGO_URL}
    JWT_SECRET: ${env:JWT_SECRET}
  httpApi:
    authorizers:
      authorizeToken:
        type: request
        functionName: authorizerFunc
        identitySource:
          - $request.header.Authorization
        resultTtlInSeconds: 300

package: 
  exclude:
    - .env

functions:
  login:
    handler: login.handler
    package: 
      exclude:
        - profile.js
        - register.js
        - utils/auth.js
    events:
      - httpApi:
          path: /login
          method: post
  register: 
    handler: register.handler
    package: 
      exclude:
        - profile.js
        - login.js
        - utils/auth.js
    events:
      - httpApi:
          path: /register
          method: post
  profile:
    handler: profile.handler
    package: 
      exclude:
        - login.js
        - register.js
        - utils/response.js
    events:
      - httpApi:
          path: /profile
          method: get
          authorizer:
            name: authorizeToken
  authorizerFunc:
    handler: utils/auth.handler
    package: 
      exclude:
        - login.js
        - register.js
        - utils/db.js
        - utils/response.js

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000