service: express-ts-lambda

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  memorySize: 256
  timeout: 10

functions:
  app:
    handler: dist/handler.handler
    events:
      - httpApi:
          path: /
          method: any
      - httpApi:
          path: /{proxy+}
          method: any

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000